import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money = n => Number(n || 0).toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function OvertimePanel({month,onChange}) {
 const {can}=useAuth(); const manage=can('payroll.manage');
 const [rows,setRows]=useState([]),[workers,setWorkers]=useState([]),[editor,setEditor]=useState(null),[form,setForm]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await axios.get('/api/payroll/overtime',{params:{month}});setRows(r.data.data);if(manage){const w=await axios.get('/api/payroll/overtime-workers');setWorkers(w.data.data.filter(u=>u.role==='Worker'&&u.is_active));}}catch(e){setError(e.response?.data?.message||'Overtime could not load.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[month,manage]);
 function open(row=null){setError('');setEditor(row||{request_key:crypto.randomUUID()});setForm(row?{user_id:row.user_id,work_date:row.work_date.slice(0,10),hours:row.minutes/60,hourly_rate:row.hourly_rate,notes:row.notes}:{user_id:'',work_date:today(),hours:'',hourly_rate:'',notes:''});}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(editor.remove)await axios.delete(`/api/payroll/overtime/${editor.id}`,{data:{reason:form.notes,version:editor.version}});else{const data={user_id:form.user_id,work_date:form.work_date,minutes:Math.round(Number(form.hours)*60),hourly_rate:Number(form.hourly_rate),notes:form.notes,version:editor.version,request_key:editor.request_key};if(editor.id)await axios.put(`/api/payroll/overtime/${editor.id}`,data);else await axios.post('/api/payroll/overtime',data);}setEditor(null);await load();onChange();}catch(e){setError(e.response?.data?.message||'Overtime could not save.');}finally{setBusy(false);}}
 const active=rows.filter(r=>!r.voided_at);
 return <section className="surface p-4 space-y-3"><header className="flex flex-wrap justify-between items-center gap-2"><div><h3 className="text-lg font-bold">Staff overtime</h3><p className="text-sm text-slate-500">{month} · {money(active.reduce((s,r)=>s+r.minutes,0)/60)} hours · Rs. {money(active.reduce((s,r)=>s+Number(r.amount),0))}</p></div>{manage&&<button className="btn btn-primary" disabled={busy} onClick={()=>open()}>Add overtime</button>}</header>
 {error&&!editor&&<p role="alert" className="form-error">{error}</p>}
 <div className="overflow-x-auto"><table className="professional-table"><thead><tr><th>Date</th><th>Worker</th><th>Hours</th><th>Rate / hour</th><th>Overtime pay</th><th>Reason</th>{manage&&<th>Actions</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className={r.voided_at?'opacity-60':''}><td>{r.work_date.slice(0,10)}</td><td>{r.user.name}</td><td>{money(r.minutes/60)}</td><td>Rs. {money(r.hourly_rate)}</td><td>Rs. {money(r.amount)}{r.voided_at&&<span className="block">Removed</span>}</td><td>{r.voided_at?r.void_reason:r.notes}</td>{manage&&<td>{!r.voided_at&&<div className="flex gap-2"><button className="btn btn-secondary" disabled={busy} onClick={()=>open(r)}>Edit</button><button className="btn btn-secondary" disabled={busy} onClick={()=>{setError('');setEditor({...r,remove:true});setForm({notes:''});}}>Remove</button></div>}</td>}</tr>)}{!rows.length&&<tr><td colSpan={7}>{loading?'Loading…':'No overtime recorded this month.'}</td></tr>}</tbody></table></div>
 {editor&&<div className="dialog-backdrop"><form className="surface operator-editor" role="dialog" aria-modal="true" aria-label="Staff overtime entry" onSubmit={submit}><h3 className="text-lg font-bold">{editor.remove?'Remove overtime':editor.id?'Edit overtime':'Add overtime'}</h3>{error&&<p role="alert" className="form-error">{error}</p>}{!editor.remove&&<><label className="field-label">Worker<select aria-label="Worker" className="field" required value={form.user_id} onChange={e=>{const w=workers.find(w=>w.id===e.target.value);setForm({...form,user_id:e.target.value,hourly_rate:w?.overtime_rate||''});}}><option value="">Select worker</option>{workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="field-label">Work date<input className="field" type="date" required max={today()} value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})}/></label><div className="staff-pay-fields"><label className="field-label">Overtime hours<input className="field" type="number" required min="0.01" max="24" step="any" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></label><label className="field-label">Rate per hour (Rs.)<input className="field" type="number" required min="0.01" step="0.01" value={form.hourly_rate} onChange={e=>setForm({...form,hourly_rate:e.target.value})}/></label></div><strong>Overtime pay: Rs. {money(Math.round(Number(form.hours||0)*60)*Number(form.hourly_rate||0)/60)}</strong></>}
 <label className="field-label">{editor.remove?'Removal reason':'Reason'}<input className="field" required maxLength={500} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><p className="text-sm text-slate-500">Overtime adds to monthly payroll. Record the actual salary payment separately.</p><footer className="flex justify-end gap-2"><button className="btn btn-secondary" type="button" disabled={busy} onClick={()=>setEditor(null)}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':editor.remove?'Confirm removal':'Save overtime'}</button></footer></form></div>}
 </section>;
}
